// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickPlace.Api.Data;

#nullable disable

namespace PickPlace.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818135019_AddPickPlaceFullSchema")]
    partial class AddPickPlaceFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PickPlace.Api.Models.AnggotaOrganisasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NamaAnggota")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("OrganisasiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganisasiId");

                    b.ToTable("AnggotaOrganisasi");
                });

            modelBuilder.Entity("PickPlace.Api.Models.ApprovalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catatan")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DiprosesPada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DosenId")
                        .HasColumnType("int");

                    b.Property<int>("PeminjamanId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipeApproval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DosenId");

                    b.HasIndex("PeminjamanId");

                    b.ToTable("ApprovalLogs");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RejectReason")
                        .HasColumnType("longtext");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("PickPlace.Api.Models.BookingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BookingLogs");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Dosen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsWakilDirektur")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NIP")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Dosen");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Notifikasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Pesan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("ReferensiId")
                        .HasColumnType("int");

                    b.Property<string>("TipeNotif")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifikasi");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Organisasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DosenPJId")
                        .HasColumnType("int");

                    b.Property<string>("NamaOrganisasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DosenPJId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Organisasi");
                });

            modelBuilder.Entity("PickPlace.Api.Models.PeminjamanRuangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlasanPembatalan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeperluanKegiatan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrganisasiId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("OrganisasiId");

                    b.HasIndex("RoomId");

                    b.ToTable("PeminjamanRuangan");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PickPlace.Api.Models.RuanganTerpinjam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PeminjamanId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PeminjamanId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("RuanganTerpinjam");
                });

            modelBuilder.Entity("PickPlace.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PickPlace.Api.Models.AnggotaOrganisasi", b =>
                {
                    b.HasOne("PickPlace.Api.Models.Organisasi", "Organisasi")
                        .WithMany("Anggota")
                        .HasForeignKey("OrganisasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisasi");
                });

            modelBuilder.Entity("PickPlace.Api.Models.ApprovalLog", b =>
                {
                    b.HasOne("PickPlace.Api.Models.Dosen", "Dosen")
                        .WithMany()
                        .HasForeignKey("DosenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickPlace.Api.Models.PeminjamanRuangan", "Peminjaman")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("PeminjamanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosen");

                    b.Navigation("Peminjaman");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Booking", b =>
                {
                    b.HasOne("PickPlace.Api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Dosen", b =>
                {
                    b.HasOne("PickPlace.Api.Models.User", "User")
                        .WithOne("Dosen")
                        .HasForeignKey("PickPlace.Api.Models.Dosen", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Notifikasi", b =>
                {
                    b.HasOne("PickPlace.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Organisasi", b =>
                {
                    b.HasOne("PickPlace.Api.Models.Dosen", "DosenPJ")
                        .WithMany("OrganisasiYangDiPJ")
                        .HasForeignKey("DosenPJId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PickPlace.Api.Models.User", "User")
                        .WithOne("Organisasi")
                        .HasForeignKey("PickPlace.Api.Models.Organisasi", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DosenPJ");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PickPlace.Api.Models.PeminjamanRuangan", b =>
                {
                    b.HasOne("PickPlace.Api.Models.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PickPlace.Api.Models.Organisasi", "Organisasi")
                        .WithMany()
                        .HasForeignKey("OrganisasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickPlace.Api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancelledBy");

                    b.Navigation("Organisasi");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PickPlace.Api.Models.RuanganTerpinjam", b =>
                {
                    b.HasOne("PickPlace.Api.Models.PeminjamanRuangan", "Peminjaman")
                        .WithOne("RuanganTerpinjam")
                        .HasForeignKey("PickPlace.Api.Models.RuanganTerpinjam", "PeminjamanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickPlace.Api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peminjaman");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Dosen", b =>
                {
                    b.Navigation("OrganisasiYangDiPJ");
                });

            modelBuilder.Entity("PickPlace.Api.Models.Organisasi", b =>
                {
                    b.Navigation("Anggota");
                });

            modelBuilder.Entity("PickPlace.Api.Models.PeminjamanRuangan", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("RuanganTerpinjam");
                });

            modelBuilder.Entity("PickPlace.Api.Models.User", b =>
                {
                    b.Navigation("Dosen");

                    b.Navigation("Organisasi");
                });
#pragma warning restore 612, 618
        }
    }
}
